services:
  event_report_manager:
    class: Yoda\EventBundle\Reporting\EventReportManager
    arguments: [@doctrine.orm.entity_manager, @router]

  event_attendees_subscriber:
    class: Yoda\EventBundle\Event\AttendeesSubscriber
    arguments: ['@user_register_manager','@mailer' ]