event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Controller"
    prefix:   /
    type:     annotation

ajax_reset_password:
    path:     /reset_password
    defaults: { _controller: UserBundle:Register:resetPassword }